"""initial_tables

Revision ID: 84c0a2590498
Revises: 
Create Date: 2026-02-09 23:55:16.288807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c0a2590498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('market', sa.Enum('KR', 'US', name='markettype'), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('timeframe', sa.Enum('H1', 'D1', name='timeframetype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('job_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('job_error', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annual_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_wins', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('equity_curve_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.Enum('KR', 'US', name='markettype'), nullable=False),
    sa.Column('timeframe', sa.Enum('H1', 'D1', name='timeframetype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', 'timeframe', 'timestamp', name='uq_market_data_identity')
    )
    op.create_index('ix_market_data_lookup', 'market_data', ['symbol', 'market', 'timeframe', 'timestamp'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.Enum('KR', 'US', name='markettype'), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('timeframe', sa.Enum('H1', 'D1', name='timeframetype'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('optimization_metric', sa.String(length=50), nullable=False),
    sa.Column('total_combinations', sa.Integer(), nullable=False),
    sa.Column('parameter_ranges', sa.JSON(), nullable=False),
    sa.Column('top_results', sa.JSON(), nullable=True),
    sa.Column('job_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('job_error', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('strategy_type', sa.String(length=100), nullable=False),
    sa.Column('default_parameters', sa.JSON(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('backtest_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('signal_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('signal_date', sa.DateTime(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('fill_date', sa.DateTime(), nullable=False),
    sa.Column('commission', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('exit_signal_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exit_fill_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit_commission', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_backtest_symbol', 'trades', ['backtest_id', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_backtest_symbol', table_name='trades')
    op.drop_table('trades')
    op.drop_table('strategy_templates')
    op.drop_table('optimization_results')
    op.drop_index('ix_market_data_lookup', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('backtests')
    # ### end Alembic commands ###
